/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 8.1.0   2018-01-20

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

******************************************************************************
*/

/* Includes */
#include "stm32l4xx.h"
#include "../Drivers/GPIO_setup.h"

/* Private macro */
//LED1 PA5
#define LED1_reg  *(long long*) 0x48000014
#define LED1_bit  (1<<5)

//LED2 PB14
#define LED2_reg  *(long long*) 0x48000414
#define LED2_bit  (1<<14)

//LED3 PC9
//LED4 PC9
#define LED3_reg  *(long long*) 0x48000814
#define LED3_bit  (1<<9)

//LED8 PE3
#define LED8_reg  *(long long*) 0x48001014
#define LED8_bit  (1<<3)

/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**  Abstract: main program
**===========================================================================
*/
int main(void){

  //setup
  //GPIO_setup(char letter, char pin, char mode, char type, char speed, char pupd)
	//C:\Users\Luke\Documents\engr\ECE497\STM32Cube_FW_L4_V1.10.0\Projects\STM32L476G-Discovery\Examples\GPIO\GPIO_IOToggle\Src
  GPIO_setup('A',  5, OUTPUT, PUSH_PULL, SLOW, NONE);
  GPIO_setup('B', 14, OUTPUT, PUSH_PULL, SLOW, NONE);
  GPIO_setup('C',  9, OUTPUT, PUSH_PULL, SLOW, NONE);
  GPIO_setup('E',  3, OUTPUT, PUSH_PULL, SLOW, NONE);

  SET_BIT(LED1_reg, LED1_bit);
  SET_BIT(LED2_reg, LED2_bit);
  SET_BIT(LED3_reg, LED3_bit);
  SET_BIT(LED8_reg, LED8_bit);

  /* Infinite loop */
  while (1){

  }
}
